name: Release
on:
  release:
    types:
      - created

jobs:

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
          always-auth: true
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          REACT_APP_DIST: electron
          REACT_APP_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish
